"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Job = { id: string; status: string; stage: string; filename: string; targetInstrument: string; error?: string | null; createdAt: number; };

export default function TranscriptionWorkspace({ email }: { email: string }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [file, setFile] = useState<File | null>(null); const [target, setTarget] = useState("auto"); const [sending, setSending] = useState(false); const [notice, setNotice] = useState("");
  async function refresh() { const response = await fetch("/api/transcription/jobs", { cache: "no-store" }); if (response.ok) setJobs((await response.json() as { jobs: Job[] }).jobs); }
  useEffect(() => { queueMicrotask(() => void refresh()); const timer = window.setInterval(() => void refresh(), 10_000); return () => window.clearInterval(timer); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file) return setNotice("请选择音频文件。"); setSending(true); setNotice(""); const body = new FormData(); body.append("file", file); body.append("target_instrument", target); body.append("source_type", "unknown"); try { const response = await fetch("/api/transcription/jobs", { method: "POST", body }); const payload = await response.json() as { error?: string; status?: string }; if (!response.ok && !payload.status) throw new Error(payload.error || "无法创建任务。"); setNotice(payload.status === "failed" ? (payload.error || "任务未能启动。") : "已安全保存音频，正在创建你的私人草稿。"); setFile(null); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "无法创建任务。"); } finally { setSending(false); } }
  return <main className="private-workspace"><header><Link href="/">← BandProject</Link><span>PRIVATE TRANSCRIPTION</span><h1>你的私人扒谱工作台</h1><p>{email} · 你的音频、草稿和修订不会发布到社区乐谱库。</p></header><section className="private-upload"><h2>创建转录草稿</h2><form onSubmit={submit}><label>音频文件<input type="file" accept="audio/wav,audio/mpeg,audio/mp4,audio/ogg,audio/flac" onChange={event => setFile(event.target.files?.[0] || null)} /></label><label>目标乐器<select value={target} onChange={event => setTarget(event.target.value)}><option value="auto">自动识别</option><option value="piano">钢琴</option><option value="guitar">吉他</option><option value="bass">贝斯</option><option value="vocals">人声</option><option value="drums">鼓</option><option value="chords">和弦</option><option value="lead-sheet">主旋律</option></select></label><button disabled={sending}>{sending ? "正在保存…" : "生成私人草稿"}</button></form>{notice && <p className="private-notice" role="status">{notice}</p>}<small>支持 WAV、MP3、M4A、OGG、FLAC，最大 50 MB。机器结果是可编辑草稿。</small></section><section className="private-jobs"><div><h2>我的任务</h2><button onClick={() => void refresh()}>刷新</button></div>{jobs.length === 0 ? <p className="private-empty">还没有任务。提交音频后，它只会出现在这里。</p> : <ul>{jobs.map(job => <li key={job.id}><div><Link href={`/transcription/${job.id}`}><b>{job.filename}</b></Link><span>{job.targetInstrument} · {new Date(job.createdAt).toLocaleString()}</span></div><em className={`job-${job.status}`}>{job.status === "completed" ? "已完成" : job.status === "failed" ? "未完成" : "处理中"}</em>{job.error && <p>{job.error}</p>}</li>)}</ul>}</section></main>;
}
